// Copyright 2026 bibihez. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Classified struct {
	CustomerLogoUrl string          `json:"customerLogoUrl"`
	CustomerName    string          `json:"customerName"`
	Flags           json.RawMessage `json:"flags"`
	Has360Tour      bool            `json:"has360Tour"`
	HasVideo        bool            `json:"hasVideo"`
	HasVirtualTour  bool            `json:"hasVirtualTour"`
	Id              int             `json:"id"`
	Media           json.RawMessage `json:"media"`
	Price           json.RawMessage `json:"price"`
	Property        json.RawMessage `json:"property"`
	Publication     json.RawMessage `json:"publication"`
	Transaction     json.RawMessage `json:"transaction"`
}

type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type Location struct {
	Approximated bool    `json:"approximated"`
	Box          string  `json:"box"`
	Country      string  `json:"country"`
	District     string  `json:"district"`
	Floor        int     `json:"floor"`
	Latitude     float64 `json:"latitude"`
	Locality     string  `json:"locality"`
	Longitude    float64 `json:"longitude"`
	Number       string  `json:"number"`
	PostalCode   string  `json:"postalCode"`
	Province     string  `json:"province"`
	Region       string  `json:"region"`
	RegionCode   string  `json:"regionCode"`
	Street       string  `json:"street"`
}

type Price struct {
	Label             string  `json:"label"`
	Language          string  `json:"language"`
	MainDisplayPrice  string  `json:"mainDisplayPrice"`
	MainValue         float64 `json:"mainValue"`
	ShortDisplayPrice string  `json:"shortDisplayPrice"`
	Type              string  `json:"type"`
}

type Property struct {
	BedroomCount        int             `json:"bedroomCount"`
	LandSurface         float64         `json:"landSurface"`
	Location            json.RawMessage `json:"location"`
	NetHabitableSurface float64         `json:"netHabitableSurface"`
	RoomCount           int             `json:"roomCount"`
	Subtype             string          `json:"subtype"`
	Title               string          `json:"title"`
	Type                string          `json:"type"`
}

type SearchResponse struct {
	Criteria         json.RawMessage `json:"criteria"`
	CurrentPage      int             `json:"currentPage"`
	MetaDescription  string          `json:"metaDescription"`
	MetaTitle        string          `json:"metaTitle"`
	Range            string          `json:"range"`
	Results          json.RawMessage `json:"results"`
	SeoFooterContent string          `json:"seoFooterContent"`
	Sort             string          `json:"sort"`
	TotalItems       int             `json:"totalItems"`
}

type Transaction struct {
	Certificate        string          `json:"certificate"`
	CertificateLogoUrl string          `json:"certificateLogoUrl"`
	HidePrice          bool            `json:"hidePrice"`
	Rental             json.RawMessage `json:"rental"`
	Sale               json.RawMessage `json:"sale"`
	Type               string          `json:"type"`
}
