// Copyright 2026 bibihez. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEnPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyType string
	var flagTransactionType string
	var flagCountries string
	var flagPage string
	var flagOrderBy string
	var flagMinPrice int
	var flagMaxPrice int
	var flagMinSurface int
	var flagMaxSurface int
	var flagMinBedroomCount int
	var flagMaxBedroomCount int
	var flagPostalCodes string
	var flagDistricts string
	var flagProvinces string
	var flagRegions string
	var flagPriceType string
	var flagIsALifeAnnuitySale bool
	var flagIsNewlyBuilt bool
	var flagHasGarden bool
	var flagHasTerrace bool
	var flagHasSwimmingPool bool
	var flagHasLift bool
	var flagHasParking bool
	var flagHasPhotos bool
	var flagHasVideo bool
	var flagMinEpcScore string
	var flagMaxEpcScore string

	cmd := &cobra.Command{
		Use:         "en",
		Short:       "List classifieds matching a property type, transaction type, and a wide set of optional filters (price, surface,...",
		Long:        "Shortcut for 'en search-classifieds'. List classifieds matching a property type, transaction type, and a wide set of optional filters (price, surface,...",
		Example:     "  immoweb-pp-cli en",
		Annotations: map[string]string{"pp:endpoint": "en.search-classifieds", "pp:method": "GET", "pp:path": "/en/search-results/{propertyType}/{transactionType}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("property-type") {
				allowedPropertyType := []string{"house", "apartment", "house-and-apartment", "new-real-estate-project-houses", "new-real-estate-project-apartments", "office", "business", "industry", "land", "garage", "exceptional-property", "public-sale"}
				validPropertyType := false
				for _, v := range allowedPropertyType {
					if flagPropertyType == v {
						validPropertyType = true
						break
					}
				}
				if !validPropertyType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "property-type", flagPropertyType, allowedPropertyType)
				}
			}
			if cmd.Flags().Changed("transaction-type") {
				allowedTransactionType := []string{"for-sale", "for-rent"}
				validTransactionType := false
				for _, v := range allowedTransactionType {
					if flagTransactionType == v {
						validTransactionType = true
						break
					}
				}
				if !validTransactionType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "transaction-type", flagTransactionType, allowedTransactionType)
				}
			}
			if cmd.Flags().Changed("order-by") {
				allowedOrderBy := []string{"relevance", "newest", "cheapest", "most_expensive", "postal_code", "relevance_price_asc", "relevance_price_desc"}
				validOrderBy := false
				for _, v := range allowedOrderBy {
					if flagOrderBy == v {
						validOrderBy = true
						break
					}
				}
				if !validOrderBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order-by", flagOrderBy, allowedOrderBy)
				}
			}
			if cmd.Flags().Changed("regions") {
				allowedRegions := []string{"BRUSSELS", "FLANDERS", "WALLONIA"}
				validRegions := false
				for _, v := range allowedRegions {
					if flagRegions == v {
						validRegions = true
						break
					}
				}
				if !validRegions {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "regions", flagRegions, allowedRegions)
				}
			}
			if cmd.Flags().Changed("price-type") {
				allowedPriceType := []string{"MONTHLY_RENTAL_PRICE", "YEARLY_RENTAL_PRICE", "MAIN_VALUE"}
				validPriceType := false
				for _, v := range allowedPriceType {
					if flagPriceType == v {
						validPriceType = true
						break
					}
				}
				if !validPriceType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "price-type", flagPriceType, allowedPriceType)
				}
			}
			if cmd.Flags().Changed("min-epc-score") {
				allowedMinEpcScore := []string{"A++", "A+", "A", "B", "C", "D", "E", "F", "G"}
				validMinEpcScore := false
				for _, v := range allowedMinEpcScore {
					if flagMinEpcScore == v {
						validMinEpcScore = true
						break
					}
				}
				if !validMinEpcScore {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "min-epc-score", flagMinEpcScore, allowedMinEpcScore)
				}
			}
			if cmd.Flags().Changed("max-epc-score") {
				allowedMaxEpcScore := []string{"A++", "A+", "A", "B", "C", "D", "E", "F", "G"}
				validMaxEpcScore := false
				for _, v := range allowedMaxEpcScore {
					if flagMaxEpcScore == v {
						validMaxEpcScore = true
						break
					}
				}
				if !validMaxEpcScore {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "max-epc-score", flagMaxEpcScore, allowedMaxEpcScore)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/en/search-results/{propertyType}/{transactionType}"
			path = replacePathParam(path, "propertyType", fmt.Sprintf("%v", flagPropertyType))
			path = replacePathParam(path, "transactionType", fmt.Sprintf("%v", flagTransactionType))
			params := map[string]string{}
			if flagCountries != "" {
				params["countries"] = fmt.Sprintf("%v", flagCountries)
			}
			if flagPage != "" {
				params["page"] = fmt.Sprintf("%v", flagPage)
			}
			if flagOrderBy != "" {
				params["orderBy"] = fmt.Sprintf("%v", flagOrderBy)
			}
			if flagMinPrice != 0 {
				params["minPrice"] = fmt.Sprintf("%v", flagMinPrice)
			}
			if flagMaxPrice != 0 {
				params["maxPrice"] = fmt.Sprintf("%v", flagMaxPrice)
			}
			if flagMinSurface != 0 {
				params["minSurface"] = fmt.Sprintf("%v", flagMinSurface)
			}
			if flagMaxSurface != 0 {
				params["maxSurface"] = fmt.Sprintf("%v", flagMaxSurface)
			}
			if flagMinBedroomCount != 0 {
				params["minBedroomCount"] = fmt.Sprintf("%v", flagMinBedroomCount)
			}
			if flagMaxBedroomCount != 0 {
				params["maxBedroomCount"] = fmt.Sprintf("%v", flagMaxBedroomCount)
			}
			if flagPostalCodes != "" {
				params["postalCodes"] = fmt.Sprintf("%v", flagPostalCodes)
			}
			if flagDistricts != "" {
				params["districts"] = fmt.Sprintf("%v", flagDistricts)
			}
			if flagProvinces != "" {
				params["provinces"] = fmt.Sprintf("%v", flagProvinces)
			}
			if flagRegions != "" {
				params["regions"] = fmt.Sprintf("%v", flagRegions)
			}
			if flagPriceType != "" {
				params["priceType"] = fmt.Sprintf("%v", flagPriceType)
			}
			if flagIsALifeAnnuitySale != false {
				params["isALifeAnnuitySale"] = fmt.Sprintf("%v", flagIsALifeAnnuitySale)
			}
			if flagIsNewlyBuilt != false {
				params["isNewlyBuilt"] = fmt.Sprintf("%v", flagIsNewlyBuilt)
			}
			if flagHasGarden != false {
				params["hasGarden"] = fmt.Sprintf("%v", flagHasGarden)
			}
			if flagHasTerrace != false {
				params["hasTerrace"] = fmt.Sprintf("%v", flagHasTerrace)
			}
			if flagHasSwimmingPool != false {
				params["hasSwimmingPool"] = fmt.Sprintf("%v", flagHasSwimmingPool)
			}
			if flagHasLift != false {
				params["hasLift"] = fmt.Sprintf("%v", flagHasLift)
			}
			if flagHasParking != false {
				params["hasParking"] = fmt.Sprintf("%v", flagHasParking)
			}
			if flagHasPhotos != false {
				params["hasPhotos"] = fmt.Sprintf("%v", flagHasPhotos)
			}
			if flagHasVideo != false {
				params["hasVideo"] = fmt.Sprintf("%v", flagHasVideo)
			}
			if flagMinEpcScore != "" {
				params["minEpcScore"] = fmt.Sprintf("%v", flagMinEpcScore)
			}
			if flagMaxEpcScore != "" {
				params["maxEpcScore"] = fmt.Sprintf("%v", flagMaxEpcScore)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "en", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyType, "property-type", "house", "Property category. `house-and-apartment` is the broad combo used by the homepage; the others are single-category... (one of: house, apartment, house-and-apartment, new-real-estate-project-houses, new-real-estate-project-apartments, office, business, industry, land, garage, exceptional-property, public-sale)")
	cmd.Flags().StringVar(&flagTransactionType, "transaction-type", "for-sale", "For sale or for rent (one of: for-sale, for-rent)")
	cmd.Flags().StringVar(&flagCountries, "countries", "BE", "Comma-separated ISO 3166-1 alpha-2 country codes")
	cmd.Flags().StringVar(&flagPage, "page", "1", "1-indexed page number (30 results per page)")
	cmd.Flags().StringVar(&flagOrderBy, "order-by", "relevance", "Sort order applied to the result set (one of: relevance, newest, cheapest, most_expensive, postal_code, relevance_price_asc, relevance_price_desc)")
	cmd.Flags().IntVar(&flagMinPrice, "min-price", 0, "Minimum price (EUR)")
	cmd.Flags().IntVar(&flagMaxPrice, "max-price", 0, "Maximum price (EUR)")
	cmd.Flags().IntVar(&flagMinSurface, "min-surface", 0, "Minimum net habitable surface (m²)")
	cmd.Flags().IntVar(&flagMaxSurface, "max-surface", 0, "Maximum net habitable surface (m²)")
	cmd.Flags().IntVar(&flagMinBedroomCount, "min-bedroom-count", 0, "Minimum number of bedrooms")
	cmd.Flags().IntVar(&flagMaxBedroomCount, "max-bedroom-count", 0, "Maximum number of bedrooms")
	cmd.Flags().StringVar(&flagPostalCodes, "postal-codes", "", "Filter by postal codes. Format is `BE-1000,2000,3000` (country prefix optional for Belgian codes).")
	cmd.Flags().StringVar(&flagDistricts, "districts", "", "Comma-separated district names (e.g. `Brussels,Mechelen`)")
	cmd.Flags().StringVar(&flagProvinces, "provinces", "", "Comma-separated province names (e.g. `Antwerp,Liege`)")
	cmd.Flags().StringVar(&flagRegions, "regions", "", "Comma-separated region codes (one of: BRUSSELS, FLANDERS, WALLONIA)")
	cmd.Flags().StringVar(&flagPriceType, "price-type", "", "Price interpretation for rentals (one of: MONTHLY_RENTAL_PRICE, YEARLY_RENTAL_PRICE, MAIN_VALUE)")
	cmd.Flags().BoolVar(&flagIsALifeAnnuitySale, "is-a-life-annuity-sale", false, "Restrict to (or exclude) life-annuity sales")
	cmd.Flags().BoolVar(&flagIsNewlyBuilt, "is-newly-built", false, "Restrict to newly-built listings")
	cmd.Flags().BoolVar(&flagHasGarden, "has-garden", false, "Only listings with a garden")
	cmd.Flags().BoolVar(&flagHasTerrace, "has-terrace", false, "Only listings with a terrace")
	cmd.Flags().BoolVar(&flagHasSwimmingPool, "has-swimming-pool", false, "Only listings with a swimming pool")
	cmd.Flags().BoolVar(&flagHasLift, "has-lift", false, "Only listings with a lift")
	cmd.Flags().BoolVar(&flagHasParking, "has-parking", false, "Only listings with parking")
	cmd.Flags().BoolVar(&flagHasPhotos, "has-photos", false, "Only listings with photos")
	cmd.Flags().BoolVar(&flagHasVideo, "has-video", false, "Only listings with video tours")
	cmd.Flags().StringVar(&flagMinEpcScore, "min-epc-score", "", "Minimum EPC (energy performance) score (one of: A++, A+, A, B, C, D, E, F, G)")
	cmd.Flags().StringVar(&flagMaxEpcScore, "max-epc-score", "", "Maximum EPC (energy performance) score (one of: A++, A+, A, B, C, D, E, F, G)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
